### ISSUE TITLE
complete dinic implementation

### ISSUE THREAD

**Issue by vignesh-m** [vignesh-m/dinic-visualization#3]
iteratively find blocking flow and subtract
maxflow/dinic.py
- [x] construct residual graph after finding block flow
- [x] iteratively find new flows
  depends on #2

**Comment by rahul13ramesh** [comment]
Is multigraph a possible input, i.e. a pair of vertices have two edges between them in same direction?
I will work on it on 6/3. Also which branch should I make changes to?

**Comment by vignesh-m** [comment]
The multigraph issue is only in the input_graph thing so its fine.We will change it later if necessary.

About the branch, anything is fine
